# Generated by Django 6.0.2 on 2026-02-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vaccine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("manufacturer", models.CharField(blank=True, max_length=120)),
                ("validity_months", models.PositiveIntegerField(default=12)),
            ],
        ),
    ]
