# Generated by Django 6.0.2 on 2026-02-10 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
        ("vaccinations", "0001_initial"),
        ("vaccines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vaccination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_at", models.DateField()),
                ("veterinarian", models.CharField(blank=True, max_length=120)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccinations",
                        to="pets.pet",
                    ),
                ),
                (
                    "vaccine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="vaccines.vaccine",
                    ),
                ),
            ],
            options={
                "unique_together": {("pet", "vaccine", "applied_at")},
            },
        ),
        migrations.DeleteModel(
            name="Vaccine",
        ),
    ]
